---
abstract: '(beta) Highly configurable recycling of syndication (RSS/Atom) feeds into tailored, guaranteed XHTML fragments.'
author:
  - 'Ashley Pond V, C<< <ashley@cpan.org> >>.'
build_requires:
  ExtUtils::MakeMaker: 6.11
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: RSSycklr
no_index:
  directory:
    - dtd
    - inc
    - t
requires:
  DateTime: 0
  Encode: 0
  File::ShareDir: 0
  GetOpt::Long: 0
  HTML::Truncate: 0
  Hash::Merge::Simple: 0
  Mouse: 0
  Pod::Usage: 0
  Template: 0
  Template::Provider::Encoding: 0.09
  Template::Stash::ForceUTF8: 0
  URI: 0
  XML::Feed: 0
  XML::LibXML: 0
  YAML: 0
version: 0.08
